### ISSUE TITLE
Plugin is not bundling the files with serverless offline start

### ISSUE THREAD

**Issue by dheerajaggarwal** [johnagan/serverless-parcel#1]
This plugin is not invoking the bundle on the following command:
`sls offline start`

**Comment by awwong1** [comment]
To make this work with `sls offline start`, just need to add an additional hook
```
    this.hooks = {
      "before:offline:start:init": this.bundle.bind(this),
      "before:package:createDeploymentArtifacts": this.bundle.bind(this),
      ...
    };
```

I made a fork more tailored to my own use case. Thank you for the plugin, @johnagan!

https://github.com/awwong1/serverless-parcel/tree/d8652fc1bf052be25a6bde4a472ca7c520dd3c31

**Comment by awwong1** [comment]
Given that there has been no response in over a week, I published my changes under a new package:
https://github.com/awwong1/serverless-simple-parcel
https://www.npmjs.com/package/serverless-simple-parcel

**Comment by johnagan** [comment]
Thanks. Glad you enjoy the plugin. Your issue didn’t have a question. If you wanted to contribute your change back, you’re welcome to open a PR for review.
